sqldb:
  dsn: "testuser:testpassword@tcp(localhost:3306)/payment_registration_system?charset=utf8mb4&parseTime=True&loc=Local"
  clean: true

nosqldb:
  uri: "mongodb://testuser:testpassword@localhost:27017/payment_registration_system?authSource=payment_registration_system"
  database: "payment_registration_system"
  clean: true

app:
  port: 8080
  read_timeout: 15
  write_timeout: 15
  graceful_shutdown: 15
  log_path: "debug_payment.log"
  is_production: false
